制御構文2の課題
ayako202103/php_exercise01 pull request #4
Opened 2022-02-27 06:49 UTC by ayako202103

提出します。
５問目がswitch文の使い方が分かりません。

2022-02-27 07:10 UTC, kzri4 commented on 05/if2_1.php
> +if ($poket_money < $fund_raising) {
while文で条件分岐できているので､ここのif文はなくて大丈夫です!

2022-02-27 07:10 UTC, kzri4 commented on 05/if2_5.php
> +}
挙動は問題ないのですが､問題に与えられている配列に新しい配列にを上書きしている形なので､`$subjects = ['数学', '英語', '理科', '社会', '国語'];`はそのまま使用して解答してみてください 🙏

2022-02-27 07:10 UTC, kzri4 commented on 05/if2_4.php
> +}
すみません・・・  if2_4.phpの問題ですが､数日前に変更いたしましたので､再度確認して解答お願いできればと思います🙏🙇

https://github.com/elites-team/23rd-century-level1/blob/master/doc/06_php/exercise01/05_if2/01.md#4-switch%E6%96%87

2022-02-27 13:45 UTC, kazu-taka requested changes
@ayako202103 
確認お願いします😊

2022-02-27 13:45 UTC, kazu-taka commented on 05/if2_5.php
> +}
@ayako202103 
VSCodeのフォーマッターを使用して(右クリックのドキュメントのフォーマット)、switch文の整形をお願いします✨

2022-02-27 13:45 UTC, kazu-taka commented on 05/if2_2.php
> +if ($poket_money < $fund_raising) {
@ayako202103 
do〜whileを抜けた時点で、募金はできないので、こちらのif文は不要になります✨

2022-02-28 12:32 UTC, kazu-taka approved these changes
@ayako202103 
1点だけ修正して頂いたらマージしてOKです✨

2022-02-28 12:32 UTC, kazu-taka commented on 05/if2_5.php
> +}
@ayako202103 
こちらでフォーマッターを使用すると以下のようになるので、再度フォーマッターを使用して修正お願いします:bow:
(花田さんのコードはcaseが中に入りすぎてます)
```php
<?php

$subjects = ['数学', '英語', '理科', '社会', '国語'];

foreach ($subjects as $subject) {
    switch ($subject) {
        case  '数学';
            echo $subject . 'の試験は明日です。' . '<br>';
            break;
        case  '英語';
            echo $subject . 'の試験は明後日です。' . '<br>';
            break;
        case  '理科';
            echo $subject . 'の試験は明々後日です。' . '<br>';
            break;
        case  '社会';
            echo $subject . 'の試験は昨日です。' . '<br>';
            break;
        case  '国語';
            echo $subject . 'の試験は中止です。' . '<br>';
            break;
    }
}
```

2022-02-28 13:15 UTC, merged